@startuml
|ユーザー|
start
:Webアプリにアクセス;
while (商品が決まった?) is (no)
  :データを検索;
  |Webアプリ|
  :検索クエリを処理;
  |データベース|
  :検索クエリを処理;
  :検索結果を返す;
  |Webアプリ|
  :検索結果を表示;
  |ユーザー|
  :結果を確認;
  :詳細をリクエスト;
  |Webアプリ|
  :検索クエリを処理;
  |データベース|
  :検索結果を返す;
  |Webアプリ|
  :検索結果を表示;
  |ユーザー|
  :結果を確認;
endwhile (yes)
:ECサイトへのリンクをクリック;
|各種ECサイト|
:ユーザーに商品を表示;
|ユーザー|
:商品を注文;
|各種ECサイト|
stop

|夜間バッチシステム|
start
:夜中の2時に起動;
while (リトライ回数 <= 3) is (yes)
  |各種ECサイト|
  :サイトをスクレイピング;
  |夜間バッチシステム|
  if (取得成功?) then (yes)
    :データベース用にデータを整形;
    |データベース|
    if (同じデータが存在?) then (no)
      :データを保存;
    endif
  else (no)
  endif
endwhile (no)
|夜間バッチシステム|
:作業を終了する;
stop
@enduml
