name: Slack Notification

on:
  push:
    paths:
      - "daily-report/2023/**"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Notify Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-status -r ${GITHUB_SHA} HEAD~1)
          echo "CHANGED_FILES: ${CHANGED_FILES}"
          FILE_LINKS=""
          while read -r status file; do
            if [[ $status == "M" ]] && [[ $file == "daily-report/2023/"* ]]; then
              FILE_LINKS+="https://github.com/${GITHUB_REPOSITORY}/blob/${GITHUB_SHA}/${file}\\n"
            fi
          done <<< "$CHANGED_FILES"
          if [ ! -z "$FILE_LINKS" ]; then
            PAYLOAD=$(printf '{"text": "柳澤幸一の日報に新規ファイルが追加されました。\\n%s"}' "${FILE_LINKS}")
            curl -X POST -H 'Content-type: application/json' --data "${PAYLOAD}" $SLACK_WEBHOOK
          fi
