name: Slack Notification

on:
  push:
    paths:
      - "daily-report/2023/**"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Notify Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${GITHUB_SHA})
          echo "CHANGED_FILES: ${CHANGED_FILES}"
          FILE_LINKS=""
          for file in $CHANGED_FILES; do
            if [[ $file == "daily-report/2023/"* ]]; then
              FILE_LINKS+="https://github.com/${GITHUB_REPOSITORY}/blob/${GITHUB_SHA}/${file}\\n"
            fi
          done
          PAYLOAD=$(printf '{"text": "日報に更新がありました。\\n%s"}' "${FILE_LINKS}")
          curl -X POST -H 'Content-type: application/json' --data "${PAYLOAD}" $SLACK_WEBHOOK
